name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  day1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: day1/

    steps:
      - uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.x'
      - run: python --version   
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
      - name: Linting
        run: flake8 . --count --show-source --statistics
      - name: Testing
        run: pytest
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run lint

  day2:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: day2/

    steps:
      - uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.x'
      - run: python --version   
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
      - name: Linting
        run: flake8 . --count --show-source --statistics
      - name: Testing
        run: pytest


  day3:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: day3/

    steps:
    - uses: actions/checkout@v2
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.34'
    - name: perlcritic
      uses: gugod/actions-perlcritic@v1.0
    - name: Run tests
      run: |
        ./run_test.sh part1.pl "Result: 198"
        ./run_test.sh part2.pl "Result: 230"
