name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  day1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: day1/

    steps:
      - uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.x'
      - run: python --version   
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
      - name: Linting
        run: flake8 . --count --show-source --statistics
      - name: Testing
        run: pytest
