name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  day1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: day1/

    steps:
      - uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.x'
      - run: python --version   
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
      - name: Linting
        run: flake8 . --count --show-source --statistics
      - name: Testing
        run: pytest
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run lint

  day2:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: day2/

    steps:
      - uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.x'
      - run: python --version   
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
      - name: Linting
        run: flake8 . --count --show-source --statistics
      - name: Testing
        run: pytest


  day3:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: day3/

    steps:
    - uses: actions/checkout@v2
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.34'
    - name: Perl Critic
      uses: Difegue/action-perlcritic@2.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          args: ./*pl
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@1.1.0
    - name: Run tests
      run: |
        ./run_test.sh part1.pl "Result: 198"
        ./run_test.sh part2.pl "Result: 230"

  day4:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: day4/

    steps:
      - uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.x'
      - run: python --version   
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
      - name: Linting
        run: flake8 . --count --show-source --statistics
      - name: Testing
        run: pytest

  day5:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: day5/

    steps:
      - uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.x'
      - run: python --version   
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
      - name: Linting
        run: flake8 . --count --show-source --statistics
      - name: Testing
        run: pytest

  day6:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: day6/

    steps:
      - uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.x'
      - run: python --version   
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
      - name: Linting
        run: flake8 . --count --show-source --statistics
      - name: Testing
        run: pytest

  day7:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: day7/

    steps:
      - uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.x'
      - run: python --version   
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
      - name: Linting
        run: flake8 . --count --show-source --statistics
      - name: Testing
        run: pytest

  day8:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: day8/

    steps:
      - uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.x'
      - run: python --version   
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
      - name: Linting
        run: flake8 . --count --show-source --statistics
      - name: Testing
        run: pytest

  day9:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: day9/
        
    steps:
      - uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.x'
      - run: python --version   
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
      - name: Linting
        run: flake8 . --count --show-source --statistics
      - name: Testing
        run: pytest